In [1]:
import pandas as pd

In [2]:
history_data = pd.read_csv("lead_90th_history_cleaned.csv")

history_data

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,2017.0,12.0
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,2018.0,12.0
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
...,...,...,...,...,...,...,...,...,...,...
6611,MI0060425,THORNAPPLE MANOR,BARRY,328.0,2024-12-31,3.0,N,2027-09-30 00:00:00,2024.0,12.0
6612,MI0061700,CURRY HOUSE ASSISTED LIVING CENTER,WEXFORD,76.0,2024-12-31,0.0,N,2027-09-30 00:00:00,2024.0,12.0
6613,MI0063476,JAMIESON NURSING HOME,ALCONA,39.0,2024-12-31,0.0,N,2027-09-30 00:00:00,2024.0,12.0
6614,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2024-06-30,0.0,N,2027-09-30 00:00:00,2024.0,6.0
6615,MI0006227,SPRING ARBOR TOWNSHIP,JACKSON,2833.0,2023-12-31,0.0,N,NaN,2023.0,12.0

In [3]:
history_data["monitoring_end_date"]

0       2017-12-31
1       2020-12-31
2       2018-12-31
3       2020-12-31
4       2023-12-31
           ...
6611    2024-12-31
6612    2024-12-31
6613    2024-12-31
6614    2024-06-30
6615    2023-12-31
Name: monitoring_end_date, Length: 6616, dtype: object

In [4]:
history_data["monitoring_end_date"] = pd.to_datetime(
    history_data["monitoring_end_date"]
)

In [5]:
history_data["monitoring_end_date"]

0      2017-12-31
1      2020-12-31
2      2018-12-31
3      2020-12-31
4      2023-12-31
          ...
6611   2024-12-31
6612   2024-12-31
6613   2024-12-31
6614   2024-06-30
6615   2023-12-31
Name: monitoring_end_date, Length: 6616, dtype: datetime64[ns]

In [6]:
pws_example = history_data[history_data["pwsid"] == "MI0040520"]
pws_example = pws_example.sort_values("monitoring_end_date")

pws_example

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,2017.0,12.0
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
2309,MI0040520,HWY M553 MOBILE ESTATES,MARQUETTE,50.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
6161,MI0040520,HWY M553 MOBILE ESTATES,MARQUETTE,50.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0

In [7]:
trend_df = (
    history_data
        .sort_values(["pwsid", "monitoring_end_date"])
)

In [8]:
trend_df

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,2018.0,12.0
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
5842,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
5,MI0000012,ADA TOWNSHIP,KENT,7155.0,2016-12-31,0.0,N,2019-09-30 00:00:00,2016.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1042,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2022-12-31,0.0,N,2023-06-30 00:00:00,2022.0,12.0
1039,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2023-06-30,0.0,N,2023-12-31 00:00:00,2023.0,6.0
1040,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2023-12-31,0.0,N,2024-06-30 00:00:00,2023.0,12.0
1041,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2024-06-30,0.0,N,2027-09-30 00:00:00,2024.0,6.0
6614,MI0070017,COREWELLHEALTH GR KALAMAZOO,KENT,165.0,2024-06-30,0.0,N,2027-09-30 00:00:00,2024.0,6.0

In [9]:
history_data["above_action_level"] = (
    history_data["lead_90th_ppb"] > 12
)

In [10]:
history_data.groupby("pwsid")["above_action_level"].any()

pwsid
MI0000011    False
MI0000012    False
MI0000020    False
MI0000030    False
MI0000040    False
             ...
MI0066700    False
MI0067020    False
MI0067101    False
MI0070016     True
MI0070017    False
Name: above_action_level, Length: 1402, dtype: bool

In [11]:
pws_example_2 = history_data[history_data["pwsid"] == "MI0070016"]
pws_example_2 = pws_example_2.sort_values("monitoring_end_date")

pws_example_2

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month,above_action_level
1038,MI0070016,COREWELL HEALTH GR FULLER,KENT,250.0,2022-12-31,0.0,N,2023-06-30 00:00:00,2022.0,12.0,False
1036,MI0070016,COREWELL HEALTH GR FULLER,KENT,250.0,2023-06-30,2.0,N,2023-12-31 00:00:00,2023.0,6.0,False
1037,MI0070016,COREWELL HEALTH GR FULLER,KENT,250.0,2023-12-31,17.0,N,2024-06-30 00:00:00,2023.0,12.0,True

In [12]:
history_data.duplicated(
    subset=["pwsid", "monitoring_end_date", "system_name", "county", "population", "lead_90th_ppb", "includes_5th_liter_or_not", "sampling_next_due_subject_to_change", "year", "month"]
).sum()

np.int64(567)

In [13]:
history_data = history_data.drop_duplicates()

In [14]:
dup_remaining = history_data[
    history_data.duplicated(
        subset=["pwsid","monitoring_end_date"],
        keep=False
    )
]

In [15]:
dup_remaining = dup_remaining.sort_values("pwsid")

In [16]:
dup_remaining

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month,above_action_level
22,MI0000030,ADDISON,LENAWEE,605.0,2023-12-31,2.0,N,2024-09-30 00:00:00,2023.0,12.0,False
5843,MI0000030,ADDISON,LENAWEE,605.0,2023-12-31,2.0,N,2026-09-30 00:00:00,2023.0,12.0,False
5289,MI0000160,"ALPENA, CITY OF",ALPENA,10128.0,2022-12-31,0.0,Y,2025-09-30 00:00:00,2022.0,12.0,False
113,MI0000160,"ALPENA, CITY OF",ALPENA,10483.0,2022-12-31,0.0,Y,2025-09-30 00:00:00,2022.0,12.0,False
110,MI0000170,ALPENA TOWNSHIP,ALPENA,5839.0,2022-12-31,0.0,N,2025-09-30 00:00:00,2022.0,12.0,False
...,...,...,...,...,...,...,...,...,...,...,...
4708,MI0066695,THE PINES OF GOODRICH (DIST1),GENESEE,40.0,2021-12-31,0.0,N,2024-09-30 00:00:00,2021.0,12.0,False
4707,MI0066695,THE PINES OF GOODRICH (DIST1),GENESEE,40.0,2021-06-30,0.0,N,2021-12-31 00:00:00,2021.0,6.0,False
5841,MI0066695,THE PINES OF GOODRICH,GENESEE,40.0,2021-12-31,0.0,N,2026-06-30 00:00:00,2021.0,12.0,False
4720,MI0066700,THE PORCHES,OTSEGO,25.0,2023-12-31,0.0,N,2024-09-30 00:00:00,2023.0,12.0,False
6189,MI0066700,THE PORCHES,OTSEGO,25.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0,False

In [17]:
dup_remaining.groupby(
    ["pwsid","monitoring_end_date"]
)["lead_90th_ppb"].nunique().value_counts()

lead_90th_ppb
1    133
2     29
3      2
4      1
Name: count, dtype: int64

In [18]:
duplicate_checking = history_data.copy()

In [19]:
duplicate_checking["lead_value_count"] = (
    history_data
    .groupby(["pwsid", "monitoring_end_date"])["lead_90th_ppb"]
    .transform("nunique")
)

In [20]:
need_review = duplicate_checking[
    duplicate_checking["lead_value_count"] > 1
]

In [21]:
need_review = need_review.sort_values(
    ["pwsid", "monitoring_end_date"]
)

In [22]:
need_review.groupby(
    ["pwsid", "monitoring_end_date"]
).size()

pwsid      monitoring_end_date
MI0000324  2019-12-31              3
           2021-12-31              2
           2022-12-31              3
           2023-12-31              4
MI0000347  2023-12-31              5
           2024-06-30             10
MI0001335  2024-12-31              2
MI0001650  2022-06-30              2
           2023-12-31              3
MI0001970  2021-12-31              2
           2024-12-31              2
MI0002070  2023-12-31              2
MI0003330  2020-06-30              3
           2020-12-31              2
           2021-12-31              2
           2023-12-31              2
MI0004140  2021-12-31              2
MI0004340  2023-12-31              2
MI0004740  2021-12-31              2
MI0004877  2024-06-30              2
           2024-12-31              2
MI0005209  2021-12-31              4
           2022-12-31              2
           2023-12-31              2
           2024-06-30              4
MI0005780  2023-12-31              3
MI0007065  2019-09-30              2
           2019-12-31              2
           2022-12-31              2
           2023-12-31              2
MI0007185  2024-12-31              2
MI0066695  2021-06-30              4
dtype: int64

In [23]:
need_review[
    need_review["pwsid"] == "MI0000324"
]

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month,above_action_level,lead_value_count
223,MI0000324,AUSABLE VALLEY COMMUNITY (APARTMENTS),OSCODA,147.0,2019-12-31,3.0,N,2022-09-30 00:00:00,2019.0,12.0,False,3
228,MI0000324,AUSABLE VALLEY COMMUNITY (HOME),OSCODA,147.0,2019-12-31,48.0,N,2020-06-30 00:00:00,2019.0,12.0,True,3
234,MI0000324,AUSABLE VALLEY COMMUNITY (VILLAGE),OSCODA,147.0,2019-12-31,0.0,N,2022-09-30 00:00:00,2019.0,12.0,False,3
225,MI0000324,AUSABLE VALLEY COMMUNITY (APARTMENTS),OSCODA,147.0,2021-12-31,2.0,N,2024-09-30 00:00:00,2021.0,12.0,False,2
231,MI0000324,AUSABLE VALLEY COMMUNITY (HOME),OSCODA,147.0,2021-12-31,0.0,N,2022-09-30 00:00:00,2021.0,12.0,False,2
226,MI0000324,AUSABLE VALLEY COMMUNITY (APARTMENTS),OSCODA,147.0,2022-12-31,5.0,N,2025-09-30 00:00:00,2022.0,12.0,False,2
232,MI0000324,AUSABLE VALLEY COMMUNITY (HOME),OSCODA,147.0,2022-12-31,0.0,N,2023-09-30 00:00:00,2022.0,12.0,False,2
236,MI0000324,AUSABLE VALLEY COMMUNITY (VILLAGE),OSCODA,147.0,2022-12-31,0.0,N,2025-09-30 00:00:00,2022.0,12.0,False,2
227,MI0000324,AUSABLE VALLEY COMMUNITY (APARTMENTS),OSCODA,147.0,2023-12-31,0.0,N,2025-09-30 00:00:00,2023.0,12.0,False,2
233,MI0000324,AUSABLE VALLEY COMMUNITY (HOME),OSCODA,147.0,2023-12-31,2.0,N,2024-09-30 00:00:00,2023.0,12.0,False,2
237,MI0000324,AUSABLE VALLEY COMMUNITY (VILLAGE),OSCODA,147.0,2023-12-31,0.0,N,2025-09-30 00:00:00,2023.0,12.0,False,2
5852,MI0000324,AUSABLE VALLEY COMMUNITY (HOME),OSCODA,147.0,2023-12-31,2.0,N,2026-09-30 00:00:00,2023.0,12.0,False,2

Try to keep all the data

In [24]:
need_review[
    need_review["pwsid"] == "MI0001335"
]

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month,above_action_level,lead_value_count
6254,MI0001335,CHARLEVOIX TOWNSHIP (DIST),CHARLEVOIX,1700.0,2024-12-31,0.0,N,2027-09-30 00:00:00,2024.0,12.0,False,2
6255,MI0001335,CHARLEVOIX TOWNSHIP (DIST2),CHARLEVOIX,1700.0,2024-12-31,3.0,N,2027-09-30 00:00:00,2024.0,12.0,False,2

In [25]:
history_clean = history_data.copy()

In [26]:
history_clean["monitoring_end_date"] = pd.to_datetime(
    history_clean["monitoring_end_date"]
)

In [27]:
duplicate_checking = history_clean.copy()

duplicate_checking["lead_value_count"] = (
    duplicate_checking
    .groupby(["pwsid", "monitoring_end_date"])["lead_90th_ppb"]
    .transform("nunique")
)

In [28]:
duplicate_checking["system_name_count"] = (
    duplicate_checking
    .groupby(["pwsid", "monitoring_end_date"])["system_name"]
    .transform("nunique")
)

In [29]:
need_review = duplicate_checking[
    duplicate_checking["lead_value_count"] > 1
]

In [30]:
need_review = need_review.sort_values(
    ["pwsid", "monitoring_end_date", "system_name"]
)

In [31]:
history_clean["above_action_level"] = (
    history_clean["lead_90th_ppb"] > 12
)

In [32]:
need_review.to_csv(
    "lead_90th_history_need_review.csv",
    index=False
)

In [33]:
history_clean.head()

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month,above_action_level
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,2017.0,12.0,False
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0,False
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,2018.0,12.0,False
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0,False
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0,False

In [34]:
history_clean.to_csv(
    "lead_90th_history_no_duplicate.csv",
    index=False
)