In [ ]:
import pandas as pd

In [2]:
history_data = pd.read_excel(
    "90th percentiles over time.xlsx",
    sheet_name="2016_2025 Duplicates Removed"
)

history_data.shape
history_data.head()

,Public Water\nSupply ID,System Name,County,Population,Last Monitoring\nPeriod End,Lead 90th\nPercentile (ppb),Includes\n5th liter?,Sampling Next Due\n(subject to change),Unnamed: 8,Unnamed: 9,...,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382,Unnamed: 16383
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT

In [3]:
history_data.head()

,Public Water\nSupply ID,System Name,County,Population,Last Monitoring\nPeriod End,Lead 90th\nPercentile (ppb),Includes\n5th liter?,Sampling Next Due\n(subject to change),Unnamed: 8,Unnamed: 9,...,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382,Unnamed: 16383
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT

In [4]:
history_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25916 entries, 0 to 25915
Columns: 16384 entries, Public Water
Supply ID to Unnamed: 16383
dtypes: datetime64[ns](4085), float64(4128), object(8171)
memory usage: 3.2+ GB

In [5]:
history_data = history_data.iloc[:, 0:8]

history_data.shape
history_data.head()

,Public Water\nSupply ID,System Name,County,Population,Last Monitoring\nPeriod End,Lead 90th\nPercentile (ppb),Includes\n5th liter?,Sampling Next Due\n(subject to change)
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00

In [6]:
history_data.shape

(25916, 8)

In [7]:
history_data.columns

Index(['Public Water\nSupply ID', 'System Name', 'County', 'Population',
       'Last Monitoring\nPeriod End', 'Lead 90th\nPercentile (ppb)',
       'Includes\n5th liter?', 'Sampling Next Due\n(subject to change)'],
      dtype='object')

In [8]:
history_data.columns = history_data.columns.str.replace("\n", " ", regex=False)
history_data.columns = history_data.columns.str.strip()
history_data.columns = history_data.columns.str.lower()
history_data.columns = history_data.columns.str.replace(" ", "_")
history_data.columns = history_data.columns.str.replace("(", "", regex=False)
history_data.columns = history_data.columns.str.replace(")", "", regex=False)

history_data.columns

Index(['public_water_supply_id', 'system_name', 'county', 'population',
       'last_monitoring_period_end', 'lead_90th_percentile_ppb',
       'includes_5th_liter?', 'sampling_next_due_subject_to_change'],
      dtype='object')

In [9]:
history_data = history_data.rename(columns={
    "public_water_supply_id": "pwsid",
    "lead_90th_percentile_ppb": "lead_90th_ppb",
    "last_monitoring_period_end": "monitoring_end_date",
    "includes_5th_liter?": "includes_5th_liter_or_not"
})

In [10]:
history_data["monitoring_end_date"] = pd.to_datetime(history_data["monitoring_end_date"])

history_data["year"] = history_data["monitoring_end_date"].dt.year
history_data["month"] = history_data["monitoring_end_date"].dt.month

In [11]:
history_data["lead_90th_ppb"] = pd.to_numeric(history_data["lead_90th_ppb"], errors="coerce")

In [12]:
print("Shape (rows, cols):", history_data.shape)

Shape (rows, cols): (25916, 10)

In [13]:
print("Columns:")
print(list(history_data.columns))

Columns:
['pwsid', 'system_name', 'county', 'population', 'monitoring_end_date', 'lead_90th_ppb', 'includes_5th_liter_or_not', 'sampling_next_due_subject_to_change', 'year', 'month']

In [14]:
key_cols = ["pwsid", "system_name", "monitoring_end_date", "lead_90th_ppb"]
print("Missing values in key columns:")
print(history_data[key_cols].isna().sum())

Missing values in key columns:
pwsid                  19299
system_name            19299
monitoring_end_date    19299
lead_90th_ppb          19300
dtype: int64

In [15]:
display(history_data.head(10))

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,2017.0,12.0
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,2018.0,12.0
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
5,MI0000012,ADA TOWNSHIP,KENT,7155.0,2016-12-31,0.0,N,2019-09-30 00:00:00,2016.0,12.0
6,MI0000012,ADA TOWNSHIP,KENT,6523.0,2019-12-31,0.0,N,2020-09-30 00:00:00,2019.0,12.0
7,MI0000012,ADA TOWNSHIP,KENT,6523.0,2020-12-31,0.0,N,2021-09-30 00:00:00,2020.0,12.0
8,MI0000012,ADA TOWNSHIP,KENT,7068.0,2021-12-31,0.0,N,2022-09-30 00:00:00,2021.0,12.0
9,MI0000012,ADA TOWNSHIP,KENT,7068.0,2022-12-31,0.0,N,2023-09-30 00:00:00,2022.0,12.0

In [16]:
print(len(history_data))
print(history_data.isna().all(axis=1).sum())

25916
19299

In [17]:
display(history_data[history_data["pwsid"].isna()].head(10))

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
5220,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5221,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5222,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5223,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5224,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5225,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5226,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5227,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5228,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5229,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [18]:
history_data = history_data.dropna(
    subset=["pwsid", "monitoring_end_date", "lead_90th_ppb"]
)

print(history_data.shape)

(6616, 10)

In [19]:
print("Final shape:", history_data.shape)
print("Unique systems:", history_data["pwsid"].nunique())
print("Year range:",
      history_data["year"].min(),
      "-",
      history_data["year"].max())

Final shape: (6616, 10)
Unique systems: 1402
Year range: 2015.0 - 2026.0

In [20]:
display(history_data.head(10))

,pwsid,system_name,county,population,monitoring_end_date,lead_90th_ppb,includes_5th_liter_or_not,sampling_next_due_subject_to_change,year,month
0,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2017-12-31,0.0,N,2020-09-30 00:00:00,2017.0,12.0
1,MI0040520,553 MOBILE ESTATES,MARQUETTE,50.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
2,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2018-12-31,0.0,N,2020-09-30 00:00:00,2018.0,12.0
3,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2020-12-31,0.0,N,2023-09-30 00:00:00,2020.0,12.0
4,MI0000011,ACME TOWNSHIP - HOPE VILLAGE,GRAND TRAVERSE,128.0,2023-12-31,0.0,N,2026-09-30 00:00:00,2023.0,12.0
5,MI0000012,ADA TOWNSHIP,KENT,7155.0,2016-12-31,0.0,N,2019-09-30 00:00:00,2016.0,12.0
6,MI0000012,ADA TOWNSHIP,KENT,6523.0,2019-12-31,0.0,N,2020-09-30 00:00:00,2019.0,12.0
7,MI0000012,ADA TOWNSHIP,KENT,6523.0,2020-12-31,0.0,N,2021-09-30 00:00:00,2020.0,12.0
8,MI0000012,ADA TOWNSHIP,KENT,7068.0,2021-12-31,0.0,N,2022-09-30 00:00:00,2021.0,12.0
9,MI0000012,ADA TOWNSHIP,KENT,7068.0,2022-12-31,0.0,N,2023-09-30 00:00:00,2022.0,12.0

In [21]:
history_data.groupby("year")["pwsid"].nunique()

year
2015.0      4
2016.0    316
2017.0    498
2018.0    502
2019.0    647
2020.0    714
2021.0    710
2022.0    643
2023.0    715
2024.0    720
2025.0      9
2026.0      1
Name: pwsid, dtype: int64

https://www.michigan.gov/egle/about/organization/drinking-water-and-environmental-health/community-water-supply/lead-and-copper-rule

"As of January 1, 2025, the lead action level has lowered from 15 parts per billion (ug/L) to 12 parts per billion (ug/L) in the Michigan Lead and Copper Rule for samples collected on or after January 1, 2025. The copper action level remains at 1.3 parts per million (mg/L). Additionally, lead action level exceedances now require a Tier 1 24-hour public notice."

In [34]:
path = "lead_90th_history_cleaned.csv"

history_data.to_csv(path, index=False)